# Generated by Django 2.1.1 on 2018-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(max_length=1000, verbose_name='摘要')),
                ('content', models.CharField(max_length=100000, verbose_name='正文')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
